// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TimeTestSub.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "TimeTestSub.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>




TimeTestSub::TimeTestSub()
{
}

TimeTestSub::~TimeTestSub()
{
}

TimeTestSub::TimeTestSub(
        const TimeTestSub& x)
{
    m_timestamp = x.m_timestamp;
    m_message = x.m_message;
}

TimeTestSub::TimeTestSub(
        TimeTestSub&& x) noexcept
{
    m_timestamp = x.m_timestamp;
    m_message = std::move(x.m_message);
}

TimeTestSub& TimeTestSub::operator =(
        const TimeTestSub& x)
{

    m_timestamp = x.m_timestamp;
    m_message = x.m_message;
    return *this;
}

TimeTestSub& TimeTestSub::operator =(
        TimeTestSub&& x) noexcept
{

    m_timestamp = x.m_timestamp;
    m_message = std::move(x.m_message);
    return *this;
}

bool TimeTestSub::operator ==(
        const TimeTestSub& x) const
{
    return (m_timestamp == x.m_timestamp &&
           m_message == x.m_message);
}

bool TimeTestSub::operator !=(
        const TimeTestSub& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member timestamp
 * @param _timestamp New value for member timestamp
 */
void TimeTestSub::timestamp(
        uint64_t _timestamp)
{
    m_timestamp = _timestamp;
}

/*!
 * @brief This function returns the value of member timestamp
 * @return Value of member timestamp
 */
uint64_t TimeTestSub::timestamp() const
{
    return m_timestamp;
}

/*!
 * @brief This function returns a reference to member timestamp
 * @return Reference to member timestamp
 */
uint64_t& TimeTestSub::timestamp()
{
    return m_timestamp;
}


/*!
 * @brief This function copies the value in member message
 * @param _message New value to be copied in member message
 */
void TimeTestSub::message(
        const std::string& _message)
{
    m_message = _message;
}

/*!
 * @brief This function moves the value in member message
 * @param _message New value to be moved in member message
 */
void TimeTestSub::message(
        std::string&& _message)
{
    m_message = std::move(_message);
}

/*!
 * @brief This function returns a constant reference to member message
 * @return Constant reference to member message
 */
const std::string& TimeTestSub::message() const
{
    return m_message;
}

/*!
 * @brief This function returns a reference to member message
 * @return Reference to member message
 */
std::string& TimeTestSub::message()
{
    return m_message;
}


// Include auxiliary functions like for serializing/deserializing.
#include "TimeTestSubCdrAux.ipp"

